-- 코드를 작성해주세요
SELECT ECOLI_DATA.ID , 
    CASE 
        WHEN ROWNUM > TOTAL * 0.75 THEN 'CRITICAL'
        WHEN ROWNUM > TOTAL * 0.5 THEN 'HIGH'
        WHEN ROWNUM > TOTAL * 0.25 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM 
    (SELECT ID, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY) AS ROWNUM
    FROM ECOLI_DATA
    ) AS ECOLI_DATA
JOIN 
    (SELECT COUNT(*) AS TOTAL
    FROM ECOLI_DATA
    ) AS TOTAL_DATA
ON 1=1
ORDER BY ECOLI_DATA.ID ASC
    