-- 코드를 작성해주세요  2, 3, 4, 
SELECT ID, GENOTYPE, 
    (SELECT GENOTYPE
    FROM ECOLI_DATA
    WHERE ID = E.PARENT_ID) AS PARENT_GENOTYPE
FROM ECOLI_DATA AS E
WHERE PARENT_ID IS NOT NULL 
    AND GENOTYPE & 
        (SELECT GENOTYPE
        FROM ECOLI_DATA
        WHERE ID = E.PARENT_ID)
        =
        (SELECT GENOTYPE
        FROM ECOLI_DATA
        WHERE ID = E.PARENT_ID)     
ORDER BY ID ASC