
SELECT SUBSTRING(A.DIFFERENTIATION_DATE,1,4) * 1 AS YEAR, B.MAX_SIZE - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A
JOIN (
    SELECT SUBSTRING(DIFFERENTIATION_DATE,1, 4) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY SUBSTRING(DIFFERENTIATION_DATE,1, 4)
) AS B ON SUBSTRING(A.DIFFERENTIATION_DATE,1,4) = B.YEAR
ORDER BY YEAR, YEAR_DEV ASC